// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('NEOBANK AUTOTEST', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('check title', async function() {
    // Test name: check title
    // Step # | name | target | value
    // 1 | storeTitle | /html/body | NEOBANK для бізнесу
    vars["NEOBANK для бізнесу"] = await driver.getTitle()
  })
  it('add phone', async function() {
    // Test name: add phone
    // Step # | name | target | value
    // 1 | open | /auth/login | 
    await driver.get("https://web.neobank.one/auth/login")
    // 2 | type | id=login | 636901699
    await driver.findElement(By.id("login")).sendKeys("636901699")
    // 3 | click | id=btnNext | 
    await driver.findElement(By.id("btnNext")).click()
    // 4 | setWindowSize | 1920x1080 | 
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    // 5 | verifyText | css=.auth-form-title |  Відкриття бізнес-рахунку можливе тільки через додаток NEOBANK для бізнесу 
    assert(await driver.findElement(By.css(".auth-form-title")).getText() == " Відкриття бізнес-рахунку можливе тільки через додаток NEOBANK для бізнесу ")
    // 6 | close |  | 
    await driver.close()
  })
})
